-- 974 rows
SELECT DISTINCT WCCMPY, WCWHS5
FROM RPT_MOD.VW_INPRDINV_INWCTLP

--989
SELECT DISTINCT CONCAT(WICMPY, WIWHS5)
FROM RPT_MOD.VW_INPRDINV_INWITMP
 

-- Why is there a difference?

SELECT DISTINCT
a.WICMPY, a.WIWHS5,b.WCCMPY, b.WCWHS5

FROM RPT_MOD.VW_INPRDINV_INWITMP a

JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON a.WICMPY = b.WCCMPY

JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON a.WIWHS5 = b.WCWHS5 


-- INNER JOIN 967
SELECT DISTINCT CONCAT(a.WICMPY, a.WIWHS5),  CONCAT(b.WCCMPY, b.WCWHS5)
FROM RPT_MOD.VW_INPRDINV_INWITMP a
JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON  CONCAT(a.WICMPY, a.WIWHS5) = CONCAT(b.WCCMPY, b.WCWHS5)


-- LEFT JOIN 988 ROWS
SELECT DISTINCT CONCAT(a.WICMPY, a.WIWHS5),  CONCAT(b.WCCMPY, b.WCWHS5)
FROM RPT_MOD.VW_INPRDINV_INWITMP a
LEFT JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON  CONCAT(a.WICMPY, a.WIWHS5) = CONCAT(b.WCCMPY, b.WCWHS5)

--LEFT EXCEPTION 22 ROWS
SELECT DISTINCT CONCAT(a.WICMPY, a.WIWHS5),  CONCAT(b.WCCMPY, b.WCWHS5)
FROM RPT_MOD.VW_INPRDINV_INWITMP a
LEFT JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON  CONCAT(a.WICMPY, a.WIWHS5) = CONCAT(b.WCCMPY, b.WCWHS5)
WHERE CONCAT(b.WCCMPY, b.WCWHS5) IS NULL

--LEFT REVIEW DATA 
SELECT DISTINCT a.*,  CONCAT(b.WCCMPY, b.WCWHS5)
FROM RPT_MOD.VW_INPRDINV_INWITMP a
LEFT JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON  CONCAT(a.WICMPY, a.WIWHS5) = CONCAT(b.WCCMPY, b.WCWHS5)
WHERE CONCAT(b.WCCMPY, b.WCWHS5) IS NULL
AND wiwhs5 = 360

-- Research
/* INWITMP appears to rep only warehouses that show sales in IIL
Meat packaging non sales do not show up, Charleston 360 is a warehouse 
why is it not showing up in IIL?
*/
SELECT *
FROM RPT_MOD.VW_INPRDDTA_INRORGP
WHERE ROWHS5 IN (196, 281, 1054, 789, 1179, 360, 575, 1210, 264, 1239, 286, 586) 


SELECT *
FROM RPT_MOD.VW_INPRDINV_INWCTLP
WHERE WCWHS5 in (196, 281, 1054, 789, 1179, 360, 575, 1210, 264, 1239, 286, 586)



-- RIGHT JOIN 973 ROWS
SELECT DISTINCT CONCAT(a.WICMPY, a.WIWHS5),  CONCAT(b.WCCMPY, b.WCWHS5)
FROM RPT_MOD.VW_INPRDINV_INWITMP a
RIGHT JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON  CONCAT(a.WICMPY, a.WIWHS5) = CONCAT(b.WCCMPY, b.WCWHS5)

--RIGHT EXCEPTION 7 records

SELECT DISTINCT CONCAT(a.WICMPY, a.WIWHS5),  CONCAT(b.WCCMPY, b.WCWHS5)
FROM RPT_MOD.VW_INPRDINV_INWITMP a
RIGHT JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON  CONCAT(a.WICMPY, a.WIWHS5) = CONCAT(b.WCCMPY, b.WCWHS5)
WHERE CONCAT(a.WICMPY, a.WIWHS5) IS NULL


-- RIGHT Review Data
SELECT DISTINCT CONCAT(a.WICMPY, a.WIWHS5),  b.*
FROM RPT_MOD.VW_INPRDINV_INWITMP a
RIGHT JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON  CONCAT(a.WICMPY, a.WIWHS5) = CONCAT(b.WCCMPY, b.WCWHS5)
WHERE CONCAT(a.WICMPY, a.WIWHS5) IS NULL

-- Evaluation
/* INWITMP Exceptions are non sales locations and INWCTLP are international
For purpose of this query Inner join will work */

-- Using COALESCE to substitute NULLS with a value
SELECT DISTINCT coalesce(b.WCNAME, 'international')
FROM RPT_MOD.VW_INPRDINV_INWITMP a
LEFT JOIN RPT_MOD.VW_INPRDINV_INWCTLP b
ON  CONCAT(a.WICMPY, a.WIWHS5) = CONCAT(b.WCCMPY, b.WCWHS5)
ORDER BY 1



/* EXERCISE - Using the above method add initmmp to your query
BONUS INVMSTP is a complex file try using the above method 
to decided with join to use */

